### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by atz** [nasa/edsc-geo#1]

**Comment by bilts** [comment]
No, just waiting on some code to be extracted.

**Comment by neonpegasu5** [comment]
It would seem it's dead

**Comment by bilts** [comment]
It's not dead. The code that will end up here is very much alive and maintained, but other activities have taken precedence over moving it here. The code to be migrated is here:

https://github.com/nasa/earthdata-search/tree/master/app/assets/javascripts/modules/map

Particularly in the arc, coordinate, geoutil, and mbr files. If you have interests / needs for this to be ported over to its own library, please let us know, since that will help inform priorities.
